name = "Linearity"
uuid = "64984655-2708-4bec-adc5-1448bd25892b"
authors = ["Gabriel Nunes <nunesgfs@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"

[targets]
test = ["Test", "PyPlot"]
